### ISSUE TITLE
"Unknown type 'svg+xml'"

### ISSUE THREAD

**Issue by Tymewalk** [OpenSprites/OpenSprites-next#56]
I tried to upload an SVG through the share page, and got this:

```
Error: Unknown type 'svg+xml'
    at Error (native)
    at getOpener (/home/timmy/ghp/OpenSprites-next/node_modules/lwip/lib/obtain.js:62:15)
    at /home/timmy/ghp/OpenSprites-next/node_modules/lwip/lib/obtain.js:46:30
    at /home/timmy/ghp/OpenSprites-next/node_modules/decree/dist/cjs/decree.js:69:29
    at Object.open (/home/timmy/ghp/OpenSprites-next/node_modules/lwip/lib/obtain.js:23:31)
    at /home/timmy/ghp/OpenSprites-next/server/main.js:37:10
    at squish (/home/timmy/ghp/OpenSprites-next/server/main.js:36:10)
    at /home/timmy/ghp/OpenSprites-next/server/main.js:952:27
    at /home/timmy/ghp/OpenSprites-next/node_modules/traceur/src/runtime/modules/generators.js:318:28
    at /home/timmy/ghp/OpenSprites-next/node_modules/traceur/src/runtime/modules/generators.js:301:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

The page says:

```
Uh-oh!
Something went wrong.
{}
```

**Comment by bates64** [comment]
For some reason, **LWIP is handling svg uploads**, which it shouldn't.

**Comment by Tymewalk** [comment]
@nanalan 

```
if (file.mimetype == "svg/xml") {
    // use something that isn't LWIP
} else {
    // use LWIP
}
```

Do we have something to handle SVG uploads?

**Comment by bates64** [comment]
**Nope** - I'm working on it now.
